# vim: ts=2 sw=2 et :
---
dist: xenial

language: python

sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - ansible-playbook test/test.yml --syntax-check
  - ansible-playbook test/test.yml
  - gitlab-ctl status
  - gitlab-ctl restart
  - gitlab-ctl status
  - gitlab-ctl reconfigure
  - gitlab-ctl restart
  - gitlab-ctl status
  - py.test -v test/test_gitlab.py

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
