---
- name: reconfigure gitlab
  command: gitlab-ctl reconfigure
  register: gitlab_restart
  failed_when: gitlab_restart.rc != 0

- name: restart gitlab-runsvdir service
  command: gitlab-ctl restart gitlabrunsvdir
